name: Hourly Bot Data

on:
  push:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"

jobs:
  bot-data:
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run start
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
